doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        
        logging: true
        driver: 'pdo_mysql'
        server_version: '8.0'
        charset: utf8
        
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
            
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: true
        
        # Enables the new implementation of proxies based on lazy ghosts instead of using the legacy implementation
        #enable_lazy_ghost_objects: false
        
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

            gedmo_tree:
                type: attribute
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
                alias: GedmoTree # (optional) it will default to the name set for the mapping
                is_bundle: false
                
            translatable:
                type: attribute
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity/MappedSuperclass"
                alias: GedmoTranslatable
                is_bundle: false
                
            loggable:
                type: attribute
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity/MappedSuperclass"
                alias: GedmoLoggable
                is_bundle: false
                
            sortable:
                type: attribute
                prefix: Gedmo\Sortable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Sortable/Entity"
                alias: GedmoSortable
                is_bundle: false

        #resolve_target_entities:
        #    IA\UsersBundle\Entity\Model\SubscriptionInterface: App\Entity\UserManagement\Subscription
