vs_application_instalator:
    resources:
        instalation_info:
            classes:
                model: App\Entity\Application\InstalationInfo
vs_application:
    resources:
        application:
            classes:
                model: App\Entity\Application\Application
        settings:
            classes:
                model: App\Entity\Application\Settings
        taxonomy:
            classes:
                model: App\Entity\Application\Taxonomy
        taxon:
            classes:
                model: App\Entity\Application\Taxon
            translation:
                classes:
                    model: App\Entity\Application\TaxonTranslation
        taxon_image:
            classes:
                model: App\Entity\Application\TaxonImage
        translation:
            classes:
                model: App\Entity\Application\Translation
        logentry:
            classes:
                model: App\Entity\Application\LogEntry
        locale:
            classes:
                model: App\Entity\Application\Locale
         
    menu:
        mainSystemMenu:
            settings:
                name: vs_application.menu.settings
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                childs:
                    locales:
                        name: vs_application.menu.available_locales
                        route: vs_application_locale_index
                    settings:
                        name: vs_application.menu.preferences
                        route: vs_application_settings_index
            taxonomy:
                name: vs_application.menu.taxonomy
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                childs:
                    list:
                        name: vs_application.menu.list_taxonomies
                        route: vs_application_taxonomy_index
                    create:
                        name: vs_application.menu.create_new_taxonomy
                        route: vs_application_taxonomy_create
                        display: true
                    update:
                        name: vs_application.menu.edit_taxonomy
                        route: vs_application_taxonomy_update
                        routeParameters:
                          id: int
                        display: false
            user_management:
                name: vs_application.menu.user_management
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                childs:
                    users_list:
                        name: vs_application.menu.users_list
                        route: vs_users_users_index
                    user_create:
                        name: vs_application.menu.create_user
                        route: vs_users_users_create
                    user_update:
                        name: vs_application.menu.update_user
                        route: vs_users_users_update
                        routeParameters:
                          id: int
                        display: false
                        
                    user_roles_list:
                        name: vs_application.menu.user_roles
                        route: vs_users_user_roles_index
                    user_roles_create:
                        name: vs_application.menu.create_role
                        route: vs_users_user_roles_create
                    user_roles_update:
                        name: vs_application.menu.update_role
                        route: vs_users_user_roles_update
                        routeParameters:
                          id: int
                        display: false
                        
        mainCmsMenu:
            cms:
                name: vs_application.menu.static_pages
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                childs:
                    list:
                        name: vs_application.menu.list_pages
                        route: vs_cms_pages_index
                    create:
                        name: vs_application.menu.create_new_page
                        route: vs_cms_pages_create
                        display: true
                    update:
                        name: vs_application.menu.edit_page
                        route: vs_cms_pages_update
                        routeParameters:
                          id: int
                        display: false
                        
                    category_list:
                        name: vs_application.menu.page_categories
                        route: vs_cms_page_categories_index
                    category_create:
                        name: vs_application.menu.create_new_page_category
                        route: vs_cms_page_categories_create
                        display: true
                    category_update:
                        name: vs_application.menu.edit_page_category
                        route: vs_cms_page_categories_update
                        routeParameters:
                          id: int
                        display: false
                        
            cms_toc:
                name: vs_application.menu.table_of_contents
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                    breadcrumb_route: vs_cms_document_index
                childs:
                    list:
                        name: vs_application.menu.document_lists
                        route: vs_cms_document_index
                    create:
                        name: vs_application.menu.create_new_document
                        route: vs_cms_document_create
                        display: true
                    update:
                        name: vs_application.menu.edit_document
                        route: vs_cms_document_update
                        routeParameters:
                          id: int
                        display: false
                    category_list:
                        name: vs_application.menu.document_categories
                        route: vs_cms_document_categories_index
                    category_create:
                        name: vs_application.menu.create_new_document_category
                        route: vs_cms_document_categories_create
                        display: true
                    category_update:
                        name: vs_application.menu.edit_document_category
                        route: vs_cms_document_categories_update
                        routeParameters:
                          id: int
                        display: false
            filemanager_vankosoft:
                name: vs_application.menu.vankoSoft_file_manager
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                childs:
                    list_filemanagers:
                        name: vs_application.menu.list_filemanagers
                        route: "vs_cms_file_manager_index"
                        display: true
                    create_filemanager:
                        name: vs_application.menu.create_new_filemanager
                        route: "vs_cms_file_manager_create"
                        display: true
                    update_filemanager:
                        name: vs_application.menu.edit_filemanager
                        route: "vs_cms_file_manager_update"
                        routeParameters:
                          id: int
                        display: false
            
            filemanager_artgris:
                name: vs_application.menu.artgris_file_manager
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                childs:
                    browse:
                        name: vs_application.menu.browse_files
                        route: vs_cms_filemanager_artgris_list
                        #uri: "/filemanager/?conf=default"
                    upload:
                        name: vs_application.menu.upload_a_file
                        route: vs_cms_filemanager_artgris_upload
        
        mainUsersSubscriptionsMenu:
            newsletter:
                name: vs_application.menu.newsletter
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                childs:
                    mailchimp_audiences_list:
                        name: vs_application.menu.list_mailchimp_audiences
                        route: vs_users_subscriptions_mailchimp_audiences_index
                    mailchimp_audiences_create:
                        name: vs_application.menu.create_new_mailchimp_audience
                        route: vs_users_subscriptions_mailchimp_audiences_create
            
            paid_services:
                name: vs_application.menu.paid_services
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                childs:
                    paid_services_category_index:
                        name: vs_application.menu.categories
                        route: vs_users_subscriptions_payed_service_category_index
                    paid_services_category_create:
                        name: vs_application.menu.create_a_category
                        route: vs_users_subscriptions_payed_service_category_create
                    paid_services_category_update:
                        name: vs_application.menu.edit_a_category
                        route: vs_users_subscriptions_payed_service_category_update
                        routeParameters:
                          id: int
                        display: false
                    paid_services_index:
                        name: vs_application.menu.paid_services
                        route: vs_users_subscriptions_payed_service_index
                    paid_services_create:
                        name: vs_application.menu.create_a_paid_service
                        route: vs_users_subscriptions_payed_service_create
                    paid_services_update:
                        name: vs_application.menu.edit_a_paid_service
                        route: vs_users_subscriptions_payed_service_update
                        routeParameters:
                          id: int
                        display: false
        
        
        mainPaymentMenu:
            gateway_config:
                name: vs_application.menu.gateway_config
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                childs:
                    gateways_index:
                        name: vs_application.menu.gateways
                        route: vs_payment_gateways_index
                    gateways_create:
                        name: vs_application.menu.create_new_gateway
                        route: vs_payment_gateways_config
                    gateways_config:
                        name: vs_application.menu.edit_a_gateway
                        route: vs_payment_gateways_config
                        routeParameters:
                          gatewayName: string
                        display: false
            payment_methods:
                name: vs_application.menu.payment_methods
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                childs:
                    gateways_index:
                        name: vs_application.menu.payment_methods
                        route: vs_payment_methods_index
                    gateways_create:
                        name: vs_application.menu.create_new_payment_method
                        route: vs_payment_methods_config
                    gateways_config:
                        name: vs_application.menu.edit_a_payment_method
                        route: vs_payment_methods_config
                        routeParameters:
                          id: int
                        display: false
        
        profileMenu:
            profile:
                name: vs_application.menu.my_profile
                route: vs_users_profile_show
                attributes:
                    iconClass: "fas fa-user mr-2"
                    target: '_self'
                    
            documentation:
                name: vs_application.menu.documentation
                uri: "http://vankosoft.org/projects/vankosoft-application-project/documentation"
                attributes:
                    iconClass: "fas fa-cog mr-2"
                    target: '_blank'
            
            language:
                name: vs_application.menu.language
                uri: "javascript:;"
                attributes:
                    id: language
                    iconClass: "fas fa-language mr-2"
                    target: '_self'
                        
            divider_1:
                isDivider: true
            
            logout:
                name: vs_application.menu.logout
                route: vs_application_logout
                attributes:
                    iconClass: "fas fa-power-off mr-2"
                    divider_prepend: false
                    divider_append: true
                    target: '_self'

