security:
    access_denied_url: /
    encoders:
        IA\UsersBundle\Entity\User:
            algorithm: auto
    providers:
        default_provider:
            entity:
                #class: App\Entity\User
                class: IA\UsersBundle\Entity\User
                property: email
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/(?!admin)
            provider:   default_provider
            anonymous:  true
            
            form_login:
                login_path: /
                check_path: /security/login_check
                username_parameter: email
                password_parameter: password
                always_use_default_target_path: false
                default_target_path:  /

    # ACL Setup
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
