security:
    access_denied_url: /
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        default_provider:
            entity:
                #class: App\Entity\User
                class: App\Entity\User
                property: email
                
    firewalls:
        #dev:
        #    pattern: ^/(_(profiler|wdt)|css|images|js)/
        #    security: false
        main:
            anonymous:  true
            
            form_login:
                login_path: /
                check_path: /security/login_check
                username_parameter: email
                password_parameter: password
                always_use_default_target_path: false
                default_target_path:  /
            logout:
                path:   /logout
                target: /
                invalidate_session: true

    # ACL Setup
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }                                              
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }                                           
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }                           
