framework:
    templating:
        engines: ['twig', 'php']
    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: IA\UsersBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    group:
        group_class: IA\UsersBundle\Entity\UserGroup
        
        