app_home:
    path: /
    controller: App\Controller\WebGuitarPro\DefaultController::index

admin_panel:
    path: /admin
    controller: App\Controller\WebGuitarPro\DefaultController::openAdminPanel

app_set_lang:
    path: /set_lang/{lang}
    controller: App\Controller\WebGuitarPro\DefaultController::setLanguage
    
app_set_locale:
    path: /set_locale/{locale}
    controller: App\Controller\WebGuitarPro\DefaultController::setLocale
    
