##########################
# Tablatures DEMO
##########################
demo_player_working:
   path: /demo/player-working/{id}
   controller: App\Controller\DemoController::playerWorking

demo_player_latest:
   path: /demo/player-latest/{id}
   controller: App\Controller\DemoController::playerLatest
    
demo_player_encore:
   path: /demo/player-encore/{id}
   controller: App\Controller\DemoController::playerEncore
   