parameters:
    ########################################################
    # Contact Page
    ########################################################
    vs_application.contact_email: 'info@bootsshop.com'
    vs_application.contact.show_address: true
    vs_application.contact.show_phone: true
    vs_application.contact.google_map: 'https://maps.google.co.uk/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=18+California,+Fresno,+CA,+United+States&amp;aq=0&amp;oq=18+California+united+state&amp;sll=39.9589,-120.955336&amp;sspn=0.007114,0.016512&amp;ie=UTF8&amp;hq=&amp;hnear=18,+Fresno,+California+93727,+United+States&amp;t=m&amp;ll=36.732762,-119.695787&amp;spn=0.017197,0.100336&amp;z=14&amp;output=embed'
    vs_application.contact.google_large_map: 'https://maps.google.co.uk/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=18+California,+Fresno,+CA,+United+States&amp;aq=0&amp;oq=18+California+united+state&amp;sll=39.9589,-120.955336&amp;sspn=0.007114,0.016512&amp;ie=UTF8&amp;hq=&amp;hnear=18,+Fresno,+California+93727,+United+States&amp;t=m&amp;ll=36.732762,-119.695787&amp;spn=0.017197,0.100336&amp;z=14'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\WebGuitarPro\DownloadTablatureController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_wgp.repository.tablature'
            - '%vs_wgp.tablatures_directory%'
