doctrine:
    dbal:
        server_version: "10.11.6-MariaDB"

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
