vs_application_taxonomy:
    resource: "@VSApplicationBundle/Resources/config/routing/taxonomy.yaml"
    prefix:   /
    options:
        expose: true
 
vs_application_password_generator:
    resource: "@VSApplicationBundle/Resources/config/routing/password_generator.yaml"
    prefix:   /
    options:
        expose: true
