vs_user_authentication:
    resource: "@VSUsersBundle/Resources/config/routing/authentication.yml"
    prefix:   /

app_login:
    path: /login
    controller: App\Controller\WebGuitarPro\AuthController::login

app_logout:
    path: /logout
    controller: App\Controller\WebGuitarPro\AuthController::logout

