vs_wgp_public_tablatures:
    path: /tablatures
    controller: App\Controller\WebGuitarPro\TablatureExtController::publicTablatures

vs_wgp_player_show:
    path: /tablatures/{id}
    controller: App\Controller\WebGuitarPro\TablatureExtController::show

tablature_read:
    path: /tablatures-ext/{id}/read
    controller: App\Controller\WebGuitarPro\TablatureExtController::read
    
vs_wgp_tablature_categories_tree_combo_with_selected:
    path: /tablatures-ext/easyui-{categoriesTaxonomyId}-{tabId}
    controller: App\Controller\WebGuitarPro\TablatureExtController::easyuiComboTreeWithSelectedSource

vs_wgp_tablature_categories_tree_combo:
    path: /tablatures-ext/easyui-categories
    controller: App\Controller\WebGuitarPro\TablatureCategoryExtController::easyuiComboTree

tablature_favorite_index:
    path: /my-favorites
    controller: App\Controller\WebGuitarPro\FavoritesController::index
    
tablature_favorite:
    path: /tablatures-ext/{id}/add-favorite
    controller: App\Controller\WebGuitarPro\FavoritesController::addFavorite
    
tablature_remove_favorite:
    path: /tablatures-ext/{id}/remove-favorite
    controller: App\Controller\WebGuitarPro\FavoritesController::removeFavorite

wgp_upoad_tablatures_limited:
    path: /error/upoad-tablatures-limited
    controller: App\Controller\WebGuitarPro\ErrorController::uploadTablaturesLimited

wgp_share_tablature_get_form:
    path: /my-shares/get-form/{tabId}
    controller: App\Controller\WebGuitarPro\ShareTablatureController::getFormAction

wgp_share_tablature_jqueryui_availableShares:
    path: /my-shares/jqueryui-available-shares
    controller: App\Controller\WebGuitarPro\ShareTablatureController::jqueryuiAvailableShares

wgp_share_tablature_easyui_targetUsersData:
    path: /my-shares/easyui-target-users-data
    controller: App\Controller\WebGuitarPro\ShareTablatureController::easyuiTargetUsersData

wgp_share_tablature_handle_form:
    path: /my-shares/handle-form
    controller: App\Controller\WebGuitarPro\ShareTablatureController::handleFormAction

wgp_share_tablature_shared_to_me:
    path: /shared-to-me
    controller: App\Controller\WebGuitarPro\SharedTablaturesController::index

wgp_share_tablature_my_shares:
    path: /my-shares
    controller: App\Controller\WebGuitarPro\SharedTablaturesController::myShares

wgp_share_tablature_my_shares_get_edit_share_form:
    path: /my-shares/get-edit-share-form/{shareId}
    controller: App\Controller\WebGuitarPro\SharedTablaturesController::getEditShareFormAction

wgp_share_tablature_my_shares_handle_edit_share_form:
    path: /my-shares/handle-edit-share-form
    controller: App\Controller\WebGuitarPro\SharedTablaturesController::handleEditShareFormAction
    
wgp_share_tablature_easyui_tablaturesData:
    path: /my-shares/easyui-tablatures-data
    controller: App\Controller\WebGuitarPro\SharedTablaturesController::easyuiTablaturesData

wgp_share_tablature_my_shares_delete_share:
    path: /my-shares/delete-share/{shareId}
    controller: App\Controller\WebGuitarPro\SharedTablaturesController::deleteShare
    
wgp_access_denied:
    path: /error/access-denied
    controller: App\Controller\WebGuitarPro\ErrorController::accessDenied

wgp_about_application:
    path: /about-application
    controller: App\Controller\WebGuitarPro\PagesController::aboutApplication

wgp_search_tablatures:
    path: /search-tablatures
    controller: App\Controller\WebGuitarPro\SearchTablaturesController::index
    
vs_wgp_tablature_download:
    path: /api/download/{id}-{originalName}
    controller: App\Controller\WebGuitarPro\DownloadTablatureController::download
