tablature_read:
    path: /tablatures-ext/{id}/read
    controller: App\Controller\WebGuitarPro\TablatureExtController::read
    
vs_wgp_tablature_categories_tree_combo_with_selected:
    path: /tablatures-ext/easyui-{categoriesTaxonomyId}-{tabId}
    controller: App\Controller\WebGuitarPro\TablatureExtController::easyuiComboTreeWithSelectedSource

tablature_favorite_index:
    path: /my-favorites
    controller: App\Controller\WebGuitarPro\FavoritesController::index
    
tablature_favorite:
    path: /tablatures-ext/{id}/add-favorite
    controller: App\Controller\WebGuitarPro\FavoritesController::addFavorite

wgp_upoad_tablatures_limited:
    path: /error/upoad-tablatures-limited
    controller: App\Controller\WebGuitarPro\ErrorController::uploadTablaturesLimited

wgp_share_tablature_get_form:
    path: /my-shares/get-form/{tabId}
    controller: App\Controller\WebGuitarPro\ShareTablatureController::getFormAction

wgp_share_tablature_jqueryui_availableShares:
    path: /my-shares/jqueryui-available-shares
    controller: App\Controller\WebGuitarPro\ShareTablatureController::jqueryuiAvailableShares

wgp_share_tablature_easyui_targetUsersData:
    path: /my-shares/easyui-target-users-data
    controller: App\Controller\WebGuitarPro\ShareTablatureController::easyuiTargetUsersData

wgp_share_tablature_handle_form:
    path: /my-shares/handle-form
    controller: App\Controller\WebGuitarPro\ShareTablatureController::handleFormAction

wgp_share_tablature_shared_to_me:
    path: /shared-to-me
    controller: App\Controller\WebGuitarPro\SharedTablaturesController::index

wgp_share_tablature_my_shares:
    path: /my-shares
    controller: App\Controller\WebGuitarPro\SharedTablaturesController::myShares

wgp_share_tablature_my_shares_get_edit_share_form:
    path: /my-shares/get-edit-share-form/{shareId}
    controller: App\Controller\WebGuitarPro\SharedTablaturesController::getEditShareFormAction

wgp_share_tablature_my_shares_handle_edit_share_form:
    path: /my-shares/handle-edit-share-form
    controller: App\Controller\WebGuitarPro\SharedTablaturesController::handleEditShareFormAction
    
wgp_share_tablature_easyui_tablaturesData:
    path: /my-shares/easyui-tablatures-data
    controller: App\Controller\WebGuitarPro\SharedTablaturesController::easyuiTablaturesData

wgp_share_tablature_my_shares_delete_share:
    path: /my-shares/delete-share/{shareId}
    controller: App\Controller\WebGuitarPro\SharedTablaturesController::deleteShare
    
wgp_access_denied:
    path: /error/access-denied
    controller: App\Controller\WebGuitarPro\ErrorController::accessDenied
