wgp_user_profile_show:
    path:     /user/profile
    controller: App\Controller\WebGuitarPro\ProfileController:indexAction
    
wgp_user_profile_change_password:
    path:     /user/profile/change-password
    controller: App\Controller\WebGuitarPro\ProfileController:changePasswordAction
