wgp_user_registration_form:
    path:     /register
    controller: App\Controller\WebGuitarPro\RegisterController:index

wgp_user_registration_confirmation:
    path:     /verify
    controller: App\Controller\WebGuitarPro\RegisterController:verify

wgp_user_forgot_password_form:
    path:     /forgot-password
    controller: App\Controller\WebGuitarPro\ForgotPasswordController:indexAction

wgp_user_forgot_password_reset:
    path:     /forgot-password/reset/{token}
    controller: App\Controller\WebGuitarPro\ForgotPasswordController:resetAction

wgp_user_profile_show:
    path:     /user/profile
    controller: App\Controller\WebGuitarPro\ProfileController:indexAction
    
wgp_user_profile_change_password:
    path:     /user/profile/change-password
    controller: App\Controller\WebGuitarPro\ProfileController:changePasswordAction
