vs_wgp_tablatures:
    resource: |
        alias: vs_wgp.tablature
        #except: ['show']
        path: /tablatures
        templates: "Pages/Tablatures"
    type: sylius.resource
    options:
        expose: true
    
vs_wgp_tablature_categories:
    resource: |
        alias: vs_wgp.tablature_category
        except: ['show']
        path: /tablature-categories
        templates: "Pages/TablatureCategories"
    type: sylius.resource
    options:
        expose: true

