services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\Application\DebugController:
        arguments:
            - '@service_container'
        tags: ['controller.service_arguments']
