parameters:
    # Pages Form Options
    ##########################################################
    vs_cms.form.pages.ckeditor_uiColor: '#ffffff'
    vs_cms.form.pages.ckeditor_extraAllowedContent: '*[*]{*}(*)'
    vs_cms.form.pages.ckeditor_toolbar: devpage_toolbar
    vs_cms.form.pages.ckeditor_extraPlugins: 'liststyle, font, justify, codesnippet, lightbox'
    vs_cms.form.pages.ckeditor_removeButtons: ''
    
    # TocPage Form Options
    ##########################################################
    vs_cms.form.toc_page.ckeditor_uiColor: '#ffffff'
    vs_cms.form.toc_page.ckeditor_extraAllowedContent: '*[*]{*}(*)'
    vs_cms.form.toc_page.ckeditor_toolbar: devpage_toolbar
    vs_cms.form.toc_page.ckeditor_extraPlugins: 'liststyle, font, justify, codesnippet, lightbox'
    vs_cms.form.toc_page.ckeditor_removeButtons: ''

    # GatewayConfig Form Options
    ##########################################################
    vs_payment.gateway_factories: ['offline', 'paypal_rest', 'paypal_express_checkout', 'paypal_pro_checkout', 'stripe_checkout', 'stripe_js']
