
home:
   path: /
   controller: App\Controller\DefaultController::index

security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /security/
  
logout:
   path: /logout

##########################
# Tablatures DEMO
##########################
demo_player:
   path: /demo/player
   controller: App\Controller\DemoController::player
   
##########################
# Tablatures
##########################
tablature_read:
   path: /tablatures/{id}/read
   controller: App\Controller\TablatureController::read
   
tablature_player:
   path: /tablatures/{id}/show
   controller: App\Controller\TablatureController::show

tablatures_new:
   path: /tablatures/new
   controller: App\Controller\TablatureController::new
   
tablatures_index:
   path: /tablatures
   controller: App\Controller\TablatureController::index
