
home:
   path: /
   controller: App\Controller\DefaultController::index

security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /security/
  
logout:
   path: /logout

##########################
# Tablatures
##########################
demo_player:
   path: /demo/player
   controller: App\Controller\DemoController::player

tablature_player:
   path: /player
   controller: App\Controller\PlayerController::player

tablatures_new:
   path: /tablatures/new
   controller: App\Controller\TablatureController::new
