
home:
   path: /
   controller: App\Controller\DefaultController::index

security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /security/
    
users_groups:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /users/groups
  
logout:
   path: /logout
   
##########################
# Tablatures
##########################
tablature_read:
   path: /tablatures/{id}/read
   controller: App\Controller\TablatureController::read
   
tablature_player:
   path: /tablatures/{id}/show
   controller: App\Controller\TablatureController::show

tablatures_new:
   path: /tablatures/new
   controller: App\Controller\TablatureController::new
   
tablatures_index:
   path: /tablatures
   controller: App\Controller\TablatureController::index

tablature_favorite:
   path: /tablatures/{id}/add-favorite
   controller: App\Controller\TablatureController::addFavorite
