services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\Application\:
        resource: '../../../../src/Controller/Application'
        tags: ['controller.service_arguments']
        autowire: true
        
    App\Controller\WebGuitarPro\:
        resource: '../../../../src/Controller/WebGuitarPro'
        tags: ['controller.service_arguments']
        autowire: true
        
    App\Controller\WebGuitarPro\AuthController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
    
    App\Controller\WebGuitarPro\DefaultController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_application.context.application'
            - '@twig'
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'

    App\Controller\WebGuitarPro\ProfileController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '%vs_users.model.users.class%'
            - '@vs_users.manager.user'
            - '@vs_users.factory.avatar_image'
            - '@vs_cms.profile_uploader'
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'

    App\Controller\WebGuitarPro\TablatureExtController:
        tags: ['controller.service_arguments']
        autowire: false
        arguments:
            - '@doctrine'
            - '@vs_application.repository.taxonomy'
            - '@vs_application.repository.taxon'
            - '@vs_users.security_bridge'
            - '@vs_wgp.repository.tablature'
            - '%vs_wgp.tablatures_directory%'
        calls:
            - [ setContainer, [ '@service_container' ] ]
            
    App\Controller\WebGuitarPro\TablatureCategoryExtController:
        tags: ['controller.service_arguments']
        autowire: false
        arguments:
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        
    App\Controller\WebGuitarPro\ErrorController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'

    App\Controller\WebGuitarPro\FavoritesController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'

    App\Controller\WebGuitarPro\RegisterController:
        public: true
        autowire: true
        tags: ['controller.service_arguments']
        arguments:
            - '@doctrine'
            - '@vs_users.manager.user'
            - '@vs_users.repository.users'
            - '@vs_users.factory.users'
            - '@vs_users.repository.user_roles'
            - '@mailer'
            - '@vs_cms.repository.pages'
            - '@security.user_authenticator'
            - '@vs_users.security.another_login_form_authenticator'
            - {
                registrationForm: '%vs_users.registration_form%',
                registerRole: '%vs_users.register_role%',
                defaultRedirect: '%vs_users.default_redirect%',
                mailerUser: '%vs_application.mailer_user%',
            }
            
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'
            
        calls:
            - setTokenGenerator: ['@?symfonycasts.verify_email.token_generator']
            - setVerifyEmailHelper: ['@?symfonycasts.verify_email.helper']
            
    App\Controller\WebGuitarPro\ShareTablatureController:
        public: true
        autowire: true
        tags: ['controller.service_arguments']
        arguments:
            - '@vs_users.repository.users'
            - '@vs_wgp.repository.tablature'
            - '@doctrine'

    App\Controller\WebGuitarPro\SharedTablaturesController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'
            - '@doctrine'
            - '@vs_wgp.repository.tablature_category'
            - '@vs_wgp.repository.tablature'

    App\Controller\WebGuitarPro\ForgotPasswordController:
        public: true
        autowire: true
        tags: ['controller.service_arguments']
        arguments:
            - '@doctrine'
            - '@vs_users.repository.reset_password_request'
            - '@vs_users.repository.users'
            - '@mailer'
            - '@vs_users.factory.reset_password_request'
            - '@vs_users.manager.user'
            - {
                defaultRedirect: '%vs_users.default_redirect%',
                mailerUser: '%vs_application.mailer_user%',
            }
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'
        calls:
            - setResetPasswordHelper: ['@?symfonycasts.reset_password.helper']
            
    App\Controller\WebGuitarPro\PagesController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'

