services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\WebGuitarPro\:
        resource: '../../../../src/Controller/WebGuitarPro'
        tags: ['controller.service_arguments']
        autowire: true
        
    App\Controller\WebGuitarPro\AuthController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
    
    App\Controller\WebGuitarPro\DefaultController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'

    App\Controller\WebGuitarPro\ProfileController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_users.manager.user'
            - '@vs_users.factory.avatar_image'
            - '@vs_cms.profile_uploader'
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'

    App\Controller\WebGuitarPro\TablatureExtController:
        tags: ['controller.service_arguments']
        autowire: false
        arguments:
            - '@vs_application.repository.taxonomy'
            - '@vs_application.repository.taxon'
            - '@vs_wgp.repository.tablature'
            - '%vs_wgp.tablatures_directory%'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        
