parameters:
    ########################################################
    # Contact Page
    ########################################################
    vs_application.contact_email: '%env(resolve:CONTACT_EMAIL)%'
    vs_application.contact.show_address: true
    vs_application.contact.show_phone: true
    vs_application.contact.google_map: 'https://maps.google.co.uk/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=18+California,+Fresno,+CA,+United+States&amp;aq=0&amp;oq=18+California+united+state&amp;sll=39.9589,-120.955336&amp;sspn=0.007114,0.016512&amp;ie=UTF8&amp;hq=&amp;hnear=18,+Fresno,+California+93727,+United+States&amp;t=m&amp;ll=36.732762,-119.695787&amp;spn=0.017197,0.100336&amp;z=14&amp;output=embed'
    vs_application.contact.google_large_map: 'https://maps.google.co.uk/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=18+California,+Fresno,+CA,+United+States&amp;aq=0&amp;oq=18+California+united+state&amp;sll=39.9589,-120.955336&amp;sspn=0.007114,0.016512&amp;ie=UTF8&amp;hq=&amp;hnear=18,+Fresno,+California+93727,+United+States&amp;t=m&amp;ll=36.732762,-119.695787&amp;spn=0.017197,0.100336&amp;z=14'


services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\Application\:
        resource: '../../../../src/Controller/Application'
        tags: ['controller.service_arguments']
        autowire: true
        
    App\Controller\WebGuitarPro\:
        resource: '../../../../src/Controller/WebGuitarPro'
        tags: ['controller.service_arguments']
        autowire: true
        
    App\Controller\WebGuitarPro\AuthController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
    
    App\Controller\WebGuitarPro\DefaultController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_application.context.application'
            - '@twig'
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'

    App\Controller\WebGuitarPro\ProfileController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '%vs_users.model.users.class%'
            - '@vs_users.manager.user'
            - '@vs_users.factory.avatar_image'
            - '@vs_cms.profile_uploader'
            - '@vs_agent.agent'
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'
            - '@vs_payment_payment'
            - '@vs_catalog.repository.pricing_plan'
            - '@vs_catalog.repository.pricing_plan_category'
            - '@vs_catalog.repository.pricing_plan_subscription'

    App\Controller\WebGuitarPro\TablatureExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - "@parameter_bag"
            - '@doctrine'
            - '@vs_application.repository.taxonomy'
            - '@vs_application.repository.taxon'
            - '@vs_users.security_bridge'
            - '@vs_wgp.repository.tablature'
            - '@vs_wgp.repository.tablature_category'
            - '%vs_wgp.tablatures_directory%'
            
    App\Controller\WebGuitarPro\TablatureCategoryExtController:
        tags: ['controller.service_arguments']
        autowire: false
        arguments:
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'
            - '@vs_wgp.repository.tablature_category'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        
    App\Controller\WebGuitarPro\ErrorController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'

    App\Controller\WebGuitarPro\FavoritesController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'

    App\Controller\WebGuitarPro\RegisterController:
        public: true
        autowire: true
        tags: ['controller.service_arguments']
        arguments:
            - '@doctrine'
            - '@translator'
            - '@vs_application.context.application'
            - '@vs_users.manager.user'
            - '@vs_users.repository.users'
            - '@vs_users.factory.users'
            - '@vs_users.repository.user_roles'
            - '@mailer'
            - '@vs_cms.repository.pages'
            - '@security.user_authenticator'
            - '@vs_users.security.another_login_form_authenticator'
            - {
                registrationForm: '%vs_users.registration_form%',
                registerRole: '%vs_users.register_role%',
                defaultRedirect: '%vs_users.default_redirect%',
                mailerUser: '%vs_application.mailer_user%',
            }
            
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'
            
        calls:
            - setTokenGenerator: ['@?symfonycasts.verify_email.token_generator']
            - setVerifyEmailHelper: ['@?symfonycasts.verify_email.helper']
            
    App\Controller\WebGuitarPro\ShareTablatureController:
        public: true
        autowire: true
        tags: ['controller.service_arguments']
        arguments:
            - '@vs_users.repository.users'
            - '@vs_wgp.repository.tablature'
            - '@doctrine'

    App\Controller\WebGuitarPro\SharedTablaturesController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'
            - '@doctrine'
            - '@vs_wgp.repository.tablature_category'
            - '@vs_wgp.repository.tablature'

    App\Controller\WebGuitarPro\ForgotPasswordController:
        public: true
        autowire: true
        tags: ['controller.service_arguments']
        arguments:
            - '@doctrine'
            - '@vs_users.repository.reset_password_request'
            - '@vs_users.repository.users'
            - '@mailer'
            - '@vs_users.factory.reset_password_request'
            - '@vs_users.manager.user'
            - {
                defaultRedirect: '%vs_users.default_redirect%',
                mailerUser: '%vs_application.mailer_user%',
            }
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'
        calls:
            - setResetPasswordHelper: ['@?symfonycasts.reset_password.helper']
            
    App\Controller\WebGuitarPro\PagesController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'
            
    App\Controller\WebGuitarPro\SearchTablaturesController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_wgp.repository.tablature'
            
    App\Controller\WebGuitarPro\DownloadTablatureController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_wgp.repository.tablature'
            - '%vs_wgp.tablatures_directory%'
            
    App\Controller\WebGuitarPro\ContactController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - {
              contactEmail: '%vs_application.contact_email%',
              showAddress: '%vs_application.contact.show_address%',
              showPhone: '%vs_application.contact.show_phone%',
              googleMap: '%vs_application.contact.google_map%',
              googleLargeMap: '%vs_application.contact.google_large_map%'
            }
            - '@mailer'
            - '@vs_users.notifications'
            - '@doctrine'
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'
