services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\WebGuitarPro\:
        resource: '../../../../src/Controller/WebGuitarPro'
        tags: ['controller.service_arguments']
        autowire: true
    
    App\Controller\WebGuitarPro\AuthController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
    
    App\Controller\WebGuitarPro\DefaultController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'

    App\Controller\WebGuitarPro\ProfileController:
        tags: ['controller.service_arguments']
        autowire: false
        arguments:
            - '@vs_users.manager.user'
            - '@vs_users.factory.avatar_image'
            - '@vs_cms.profile_uploader'
            
    App\Controller\WebGuitarPro\RegisterController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_users.manager.user'
            - '@vs_users.repository.users'
            - '@vs_users.repository.user_roles'
            - '@mailer'
        calls:
            - setTokenGenerator: ['@?symfonycasts.verify_email.token_generator']
            - setVerifyEmailHelper: ['@?symfonycasts.verify_email.helper']

    App\Controller\WebGuitarPro\ForgotPasswordController:
        public: true
        autowire: true
        tags: ['controller.service_arguments']
        arguments:
            - '@vs_users.repository.reset_password_request'
            - '@vs_users.repository.users'
            - '@mailer'
        calls:
            - setResetPasswordHelper: ['@?symfonycasts.reset_password.helper']

