parameters:
    vs_application.menu.config_file: "%kernel.project_dir%/config/applications/web-guitar-pro/packages/vs_application.yaml"
    vs_application.main_menus: ['mainWebGuitarProMenu', 'profileMenu']

services:
    # Custom Menus
    ######################################################
    vs_wgp.main_menu:
        autowire: false
        class: Knp\Menu\MenuItem
        factory: ["@vs_app.menu_builder", mainMenu]
        arguments: ["@knp_menu.factory", 'mainWebGuitarProMenu']
        tags:
            - { name: knp_menu.menu, alias: mainWebGuitarPro }
