services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    # VS Catalog Controllers
    ##############################   
    App\Controller\WebGuitarPro\PricingPlanCheckoutController:
        public: true
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']
        arguments:
            - '@doctrine'
            - '@event_dispatcher'
            - '@vs_users.security_bridge'
            - '@vs_payment.factory.order'
            - '@vs_payment.repository.order'
            - '@vs_payment.factory.order_item'
            - '@vs_payment.repository.payment_method'
            - '@vs_payment_payment'
            - '@vs_payment.order_factory'
            - '@vs_payment.repository.gateway_config'
            - '@vs_catalog.repository.pricing_plan_category'
            - '@vs_catalog.repository.pricing_plan'
            - '@vs_catalog.repository.pricing_plan_subscription'
            
            - '@vs_application.repository.taxonomy'
            - '%vs_wgp.tablature-categories.taxonomy_code%'
        calls:
            - [ setContainer, [ '@service_container' ] ]
            
            