parameters:
    vs_wgp.tablatures_directory: "%kernel.project_dir%/public/shared_media/gaufrette/tablatures"
    vs_wgp.unpaid_tablature_storage: 10
    
services:
    _defaults:
        #autowire: true
        #autoconfigure: true
        public: true

    vs_wgp.tablature_file_path_generator:
        class: App\Component\TablatureUploader\FilePathGenerator
        
    vs_wgp.tablature_uploader:
        class: App\Component\TablatureUploader\TablatureUploader
        arguments:
            - '@oneup_flysystem.vs_wgp_tablatures_filesystem'
            - '@vs_wgp.tablature_file_path_generator'
