resources:
    App\Entity\TablatureCategory:
        operations:
            my_categories_get:
                class: ApiPlatform\Metadata\GetCollection
                method: GET
                uriTemplate: /my-categories
                controller: App\Controller\Api\MyTablaturesCategoriesController
                normalizationContext:
                    groups: ['tablature-category:read']
            
            category_post:
                class: ApiPlatform\Metadata\Post
                method: POST
                uriTemplate: /my-categories/new
                controller: App\Controller\Api\CreateCategoryController
                
                read: false # Disable ReadListener
                write: false
                deserialize: false,
                
                normalizationContext:
                    groups: ['tablature-category:read']
                denormalizationContext:
                    groups: ['tablature-category:create']
            
            category_put:
                class: ApiPlatform\Metadata\Put
                method: PUT
                uriTemplate: /my-categories/{id}
                controller: App\Controller\Api\EditCategoryController
                
                read: false # Disable ReadListener
                write: false
                deserialize: false,
                
                normalizationContext:
                    groups: ['tablature-category:read']
                denormalizationContext:
                    groups: ['tablature-category:update']
                
            category_delete:
                class: ApiPlatform\Metadata\Delete
                method: DELETE
                uriTemplate: /my-categories/{id}
                controller: App\Controller\Api\DeleteCategoryController

        properties:
            id:
                identifier: true
                writeable: false
                required: false
            parent:
                writeable: true
                required: false
            code:
                writeable: true
                required: false
            enabled:
                writeable: true
            name:
                writeable: true
                required: true
            description:
                writeable: true
                required: false
                
#             user:
#                 writeable: true
#                 required: true
            createdBy:
                writeable: false
            updatedBy:
                writeable: false
            createdAt:
                writeable: false
            updatedAt:
                writeable: false
