sylius_resource:
    #translation:
        #default_locale: '%locale%'
        #locale_provider: sylius.translation.locale_provider.contextual
        #available_locales_provider: sylius.translation.locales_provider
    resources:
        vs_wgp.tablature_category:
            driver: doctrine/orm
            classes:
                model:      App\Entity\TablatureCategory
                repository: App\Repository\TablatureCategoryRepository
                controller: App\Controller\WebGuitarPro\TablatureCategoryController
                form:       App\Form\TablatureCategoryForm
                
        vs_wgp.tablature:
            driver: doctrine/orm
            classes:
                model:      App\Entity\Tablature
                repository: App\Repository\TablatureRepository
                controller: App\Controller\WebGuitarPro\TablatureController
                form:       App\Form\TablatureForm
        vs_wgp.tablature_file:
            driver: doctrine/orm
            classes:
                model:      App\Entity\TablatureFile
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository

