twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    
    globals:
        applicationTitle: '%applicationTitle%'
        lang: '%lang%'
        locale: '%locale%'
        formCreateAccount: '%vs_users.form_create_account%'
        alerts: '@vs_app.twig.alerts'
        languages: '%languages%'
        installedBundles: '%kernel.bundles%'
        app_environment: '%env(APP_ENV)%'
        alphatabUseCdn: '%vs_wgp.alphatab.use_cdn%'
        
    form_themes: [
      'bootstrap_4_layout.html.twig',
      '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    ]
    