twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    
    globals:
        app_environment: '%env(APP_ENV)%'
        applicationCompany: '%applicationCompany%'
        applicationTitle: '%applicationTitle%'
        hasTopSearch: '%hasTopSearch%'
        locale: '%locale%'
        formCreateAccount: '%vs_users.form_create_account%'
        alerts: '@vs_app.twig.alerts'
        installedBundles: '%kernel.bundles%'
        alphatabUseCdn: '%vs_wgp.alphatab.use_cdn%'
        alphatabUseVersion: '%vs_wgp.alphatab.version%'
        analyticsMeasurementId: '%env(GOOGLE_MEASUREMENT_ID)%'
        
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    