vs_application_instalator:
    resources:
        instalation_info:
            classes:
                model: App\Entity\Application\InstalationInfo
vs_application:
    project_type: extended_application
    
    resources:
        application:
            classes:
                model: App\Entity\Application\Application
        settings:
            classes:
                model: App\Entity\Application\Settings
        taxonomy:
            classes:
                model: App\Entity\Application\Taxonomy
        taxon:
            classes:
                model: App\Entity\Application\Taxon
            translation:
                classes:
                    model: App\Entity\Application\TaxonTranslation
        taxon_image:
            classes:
                model: App\Entity\Application\TaxonImage
        translation:
            classes:
                model: App\Entity\Application\Translation
        logentry:
            classes:
                model: App\Entity\Application\LogEntry
        locale:
            classes:
                model: App\Entity\Application\Locale
        cookie_consent_translation:
            classes:
                model: App\Entity\Application\CookieConsentTranslation
        tags_whitelist_context:
            classes:
                model: App\Entity\Application\TagsWhitelistContext
        tags_whitelist_tag:
            classes:
                model: App\Entity\Application\TagsWhitelistTag
        widget_group:
            classes:
                model: App\Entity\Application\WidgetGroup
        widget:
            classes:
                model: App\Entity\Application\Widget
        widgets_registry:
            classes:
                model: App\Entity\Application\WidgetsRegistry

    menu:
        mainWebGuitarProMenu:
            latest_tablatures:
                name: vs_application.menu.site_main.latest_tablatures
                route: app_home
            my_tabulatures:
                name: vs_application.menu.site_main.my_tablatures
                route: vs_wgp_tablature_index
            my_favorites:
                name: vs_application.menu.site_main.my_favorites
                route: tablature_favorite_index
            my_shares:
                name: vs_application.menu.site_main.my_shares
                route: wgp_share_tablature_my_shares
            shared_to_me:
                name: vs_application.menu.site_main.shared_to_me
                route: wgp_share_tablature_shared_to_me

#         profileMenu:
#             profile:
#                 name: vs_application.menu.my_profile
#                 route: vs_users_profile_show
#                 attributes:
#                     iconClass: "fas fa-user me-2"
#                     target: '_self'
#                     
#             language:
#                 name: vs_application.menu.language
#                 uri: "javascript:;"
#                 attributes:
#                     id: language
#                     iconClass: "fas fa-language me-2"
#                     target: '_self'
#                     
#             divider_0:
#                 isDivider: true
#                 
#             documentation:
#                 name: vs_application.menu.documentation
#                 uri: "javascript:;"
#                 attributes:
#                     iconClass: "fas fa-cog me-2"
#                     
#             about:
#                 name: vs_application.menu.about_application
#                 route: wgp_about_application
#                 attributes:
#                     iconClass: "fas fa-cog me-2"
#                     
#             pricing_plans:
#                 name: vs_application.menu.site_main.extend_your_tablatures_store
#                 route: vs_payment_pricing_plans
#                 #route: vs_catalog_pricing_plan_index
#                 attributes:
#                     iconClass: "fas fa-cog me-2"
#             
#             divider_1:
#                 isDivider: true
#                 
#             alphatab_demo_1:
#                 name: 'Alphatab Demo 1'
#                 route: demo_pages_alphatab
#                 attributes:
#                     id: alphatab_demo
#                     iconClass: "fas fa-cog me-2"
#                 
#             divider_2:
#                 isDivider: true
#             
#             logout:
#                 name: vs_application.menu.logout
#                 route: app_logout
#                 attributes:
#                     iconClass: "fas fa-power-off me-2"
#                     divider_prepend: false
#                     divider_append: true
#                     target: '_self'

        profileMenu:
            profile:
                name: vs_application.menu.my_profile
                route: vs_users_profile_show
                attributes:
                    iconClass: "mdi mdi-account-circle text-muted fs-16 align-middle me-1"
                    
            documentation:
                name: vs_application.menu.documentation
                uri: "javascript:;"
                attributes:
                    iconClass: "mdi mdi-lifebuoy text-muted fs-16 align-middle me-1"
                    
            about:
                name: vs_application.menu.about_application
                route: wgp_about_application
                attributes:
                    iconClass: "mdi mdi-lifebuoy text-muted fs-16 align-middle me-1"
                  
            divider_1:
                isDivider: true
                  
            pricing_plans:
                name: vs_application.menu.site_main.extend_your_tablatures_store
                route: vs_payment_pricing_plans
                #route: vs_catalog_pricing_plan_index
                attributes:
                    iconClass: "fas fa-cog me-1"
            
            alphatab_demo_1:
                name: 'Alphatab Demo 1'
                route: demo_pages_alphatab
                attributes:
                    id: alphatab_demo
                    iconClass: "fas fa-cog me-1"
                
            divider_2:
                isDivider: true
                
            logout:
                name: vs_application.menu.logout
                route: app_logout
                attributes:
                    iconClass: "mdi mdi-logout text-muted fs-16 align-middle me-1"
                    

     