framework:
    assets:
        packages:
            default:
                json_manifest_path: '%kernel.project_dir%/public/web-guitar-pro/build/default/manifest.json'
            web-guitar-pro-vuejs:
                json_manifest_path: '%kernel.project_dir%/public/shared_assets/build/web-guitar-pro-vuejs/manifest.json'
            web-guitar-pro-reactjs:
                json_manifest_path: '%kernel.project_dir%/public/shared_assets/build/web-guitar-pro-reactjs/manifest.json'
            web-guitar-pro-angularjs:
                json_manifest_path: '%kernel.project_dir%/public/shared_assets/build/web-guitar-pro-angularjs/manifest.json'
            web-guitar-pro-velzon-sass:
                json_manifest_path: '%kernel.project_dir%/public/shared_assets/build/web-guitar-pro-velzon-saas/manifest.json'
webpack_encore:
    output_path: '%kernel.project_dir%/public/web-guitar-pro/build/default'
    builds:
        defaultConfig: '%kernel.project_dir%/public/web-guitar-pro/build/default'
        
        WebGuitarPro_VueJs: '%kernel.project_dir%/public/shared_assets/build/web-guitar-pro-vuejs'
        WebGuitarPro_ReactJs: '%kernel.project_dir%/public/shared_assets/build/web-guitar-pro-reactjs'
        WebGuitarPro_AngularJs: '%kernel.project_dir%/public/shared_assets/build/web-guitar-pro-angularjs'
        WebGuitarPro_VelzonSaas: '%kernel.project_dir%/public/shared_assets/build/web-guitar-pro-velzon-saas'
