App\Entity\TablatureCategory:
    attributes:
        id:
            groups: ['tablature-category:read']
        parent:
            groups: ['tablature-category:read', 'tablature-category:create', 'tablature-category:update']
        code:
            groups: ['tablature-category:read', 'tablature-category:create', 'tablature-category:update']
        name:
            groups: ['tablature-category:read', 'tablature-category:create', 'tablature-category:update']
        description:
            groups: ['tablature-category:read', 'tablature-category:create', 'tablature-category:update']
        children:
            groups: ['tablature-category:read', 'tablature-category:create', 'tablature-category:update']
        tablatures:
            groups: ['tablature-category:read', 'tablature-category:create', 'tablature-category:update']
