App\Entity\TablatureCategory:
    attributes:
        id:
            groups: ['tablature-category:read']
        taxon:
            groups: ['tablature-category:read', 'tablature-category:create', 'tablature-category:update']
        children:
            groups: ['tablature-category:read', 'tablature-category:create', 'tablature-category:update']
        tablatures:
            groups: ['tablature-category:read', 'tablature-category:create', 'tablature-category:update']


App\Entity\Application\Taxon:
    attributes:
        name:
            groups: ['tablature-category:read']


