App\Entity\Tablature:
    attributes:
        id:
            groups: ['tablature:read', 'tablature-category:read']
        artist:
            groups: ['tablature:read', 'tablature:create', 'tablature:update', 'tablature-category:read']
        song:
            groups: ['tablature:read', 'tablature:create', 'tablature:update', 'tablature-category:read']
        enabled:
            groups: ['tablature:read', 'tablature:create', 'tablature:update', 'tablature-category:read']

        tablatureFile:
            groups: ['tablature:read', 'tablature-category:read']
#         categories:
#             groups: ['tablature:read', 'tablature:create', 'tablature:update', 'tablature-category:read']
        
        user:
            groups: ['tablature:read']
        
        createdBy:
            groups: ['tablature:read', 'tablature-category:read']
        updatedBy:
            groups: ['tablature:read', 'tablature-category:read']
        createdAt:
            groups: ['tablature:read', 'tablature-category:read']
        updatedAt:
            groups: ['tablature:read', 'tablature-category:read']

App\Entity\TablatureFile:
    attributes:
        originalName:
            groups: ['tablature:read', 'tablature-category:read']
        path:
            groups: ['tablature:read', 'tablature-category:read']


