payum:
    gateways:
        core:
            payum.template.obtain_token: '@VSPayment/Payum/obtainStripeJsToken.html.twig'
            payum.template.obtain_credit_card: '@VSPayment/Payum/obtainCreditCard.html.twig'
            payum.template.obtain_coupon_code: '@VSPayment/Payum/obtainCouponCode.html.twig'

vs_payment:
    # Supported Storages: doctrine_orm, filesystem
    token_storage: doctrine_orm
    
    http_client:
        verify_peer: true
        verify_host: true
    
    resources:
        gateway_config:
            classes:
                model: App\Entity\Payment\GatewayConfig
        payment_method:
            classes:
                model: App\Entity\Payment\PaymentMethod
        payment:
            classes:
                model: App\Entity\Payment\Payment
        payment_token:
            classes:
                model: App\Entity\Payment\PaymentToken
        order:
            classes:
                model: App\Entity\Payment\Order
        order_item:
            classes:
                model: App\Entity\Payment\OrderItem
        currency:
            classes:
                model: App\Entity\Payment\Currency
        exchange_rate:
            classes:
                model: App\Entity\Payment\ExchangeRate
        promotion:
            classes:
                model: App\Entity\Payment\Promotion
        promotion_coupon:
            classes:
                model: App\Entity\Payment\PromotionCoupon
        promotion_action:
            classes:
                model: App\Entity\Payment\PromotionAction
        promotion_rule:
            classes:
                model: App\Entity\Payment\PromotionRule
        adjustment:
            classes:
                model: App\Entity\Payment\Adjustment
        customer_group:
            classes:
                model: App\Entity\Payment\CustomerGroup
        exchange_rate_service:
            classes:
                model: App\Entity\Payment\ExchangeRateService
