vs_users_subscriptions:
    #mailchimp_api_key: '%env(MAILCHIMP_API_KEY)%'
    mailchimp_api_key: 'NOT_DEFINED'
    
    resources:
        mailchimp_audiences:
            classes:
                model: App\Entity\UsersSubscriptions\MailchimpAudience
        newsletter_subscriptions:
            classes:
                model: App\Entity\UsersSubscriptions\NewsletterSubscription
        payed_service:
            classes:
                model: App\Entity\UsersSubscriptions\PayedService
        payed_service_subscription_period:
            classes:
                model: App\Entity\UsersSubscriptions\PayedServiceSubscriptionPeriod
        payed_service_attribute:
            classes:
                model: App\Entity\UsersSubscriptions\PayedServiceAttribute

